ui: mocha-bdd
browsers:
  - name: chrome
    version: [26, -1..latest]
  - name: firefox
    version: [4, -1..latest]
  - name: safari
    version: [5, -1..latest]
  - name: opera
    version: [12, -1..latest]
  - name: ie
    version: [9, -1..latest]
  - name: microsoftedge
    version: [20, latest]
  - name: ipad
    version: [5.1, -1..latest]
  - name: iphone
    version: [5.1, -1..latest]
  - name: android
    version: [4.0, -1..latest]